### ISSUE TITLE
generalize "You called for help..." display blocks so it can be reused for other soul events

### ISSUE THREAD

**Issue by WesLSmith** [TheAfroOfDoom/omega-flowey-minecraft-remastered#136]
In order to avoid duplicating "call for help" display block code multiple times we'll need to abstract this in a similar way to the "call for help" buttons so it can be used for every soul event.

**Comment by TheAfroOfDoom** [comment]
this ticket could also entail summoning the display under a new TV "locator". we use locators a lot already to sync the position of entities with an AJ model that is animating 

see: https://animated-java.dev/docs/the-blueprint-format/locators

**Comment by TheAfroOfDoom** [comment]
I am relatively fine with the SAVED text only showing up if the TV model exists to simplify some code

**Comment by WesLSmith** [comment]
Put this under Entity/Soul shared?
