### ISSUE TITLE
convert machine-specific references so repo is developer-agnostic by adding `.env` file

### ISSUE THREAD

**Issue by TheAfroOfDoom** [TheAfroOfDoom/omega-flowey-minecraft-remastered#2]
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/3481f0753692aa94893dfecd8c0642b2fb08a255/omega-flowey.code-workspace#L9

- should add a `.env` file with relevant variables for paths like `%appdata%` (or path to `.minecraft` directory)

- convert `.code-workspace` from committed file to a `.code-workspace.SAMPLE` file

**Comment by aidant19** [comment]
Idea would be to have configurable environment variables that overwrite the workspace file for your local environment? Could be implemented in a script locally as I doubt VSCode support for this will exist before the project is completed.

**Comment by TheAfroOfDoom** [comment]
a common pattern I've seen is to gitignore the actual workspace/.env file and add a `workspace.TEMPLATE`

then users copy it and rename to `workspace` and can change to their local stuff accordingly

problem is the template being updated won't update the gitignored file. not sure what to do in this case other than have the user manually update?
