### ISSUE TITLE
add script to extract `world.zip` to developer's `.minecraft/saves` folder

### ISSUE THREAD

**Issue by TheAfroOfDoom** [TheAfroOfDoom/omega-flowey-minecraft-remastered#53]
we keep a working backup of the world save at [world.zip](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/main/world.zip) in this repo

right now to actually use it the user has to manually copy+paste / extract it to their `.minecraft/saves` folder

---

TODO of this ticket is to create a script that reads in the user's `.minecraft/saves` path through an environment variable and auto-extracts `world.zip` to there.

probably something like:

```bash
yarn sync down
```

(as opposed to `yarn sync [up]` which already exists now to zip and backup the world to the repo)

**Comment by aidant19** [comment]
Could (should?) be implemented with #2

**Comment by TheAfroOfDoom** [comment]
this should be pretty easy if you just make a new script in `./package-scripts/` and call it with `node ./package-scripts/blah.js`

probably use this package: https://www.npmjs.com/package/extract-zip
