### ISSUE TITLE
add script to compile all `.ajmodel` files and add animated java files (all but the `.ajmodel` files) to `.gitignore`

### ISSUE THREAD

**Issue by TheAfroOfDoom** [TheAfroOfDoom/omega-flowey-minecraft-remastered#8]
# summary

since they are auto generated by the [Animated Java](https://github.com/Animated-Java/animated-java) Blockbench plugin, there's no reason to commit them all to the repo.

it's unclear however if it's even possible to do this (with current tooling), since there isn't (?) a dedicated Blockbench CLI for us to pass the `.ajmodel` files into

---

## definition of done

add the ability to:

1. call the Blockbench API through the CLI
2. add an endpoint to talk to the Animated Java plugin and pass in a glob of `.ajmodel` files and run AJ's export method on them

**Comment by aidant19** [comment]
Blockbench plugin development planned to enable CLI
