### ISSUE TITLE
determine system to display Flowey's speech-text / soul event text

### ISSUE THREAD

**Issue by TheAfroOfDoom** [TheAfroOfDoom/omega-flowey-minecraft-remastered#82]
examples from Undertale / the old map:

## `* You called for help` (ACTing during a soul event)
| Undertale | original map |
|-|-|
| <img alt="undertale-soul-event" src="https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/assets/13565346/1a6417db-6766-4ed4-b987-bbb260772570" width=400 /> | ![original-map-soul-event](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/assets/13565346/72b96e27-5f1d-4152-9cc1-ee61eb343ae6) |
| https://youtu.be/RJ4kumxv_1k?t=147 | https://youtu.be/2IprmKr31pU?t=93 |

for the [Jevil map](https://youtu.be/mDRRRGh3JW4?t=54) we just put anything text-related directly into chat. (some stuff used `/title` or `/subtitle`, but mostly just used `/tellraw`). this is also an option but we might be able to do better.

maybe with the new text displays? https://minecraft.wiki/w/Display#Text_Displays

**Comment by WesLSmith** [comment]
Gonna give this a shot over the next week or so
